name: Tests

on:

  push:
    branches:
      - master

  pull_request:

jobs:

  tests:

    name: PHPUnit
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: ['5.5', '5.6', '7.1', '7.2', '7.3', '7.4', '8.0']
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        experimental: [false]
        include:
          - os: 'ubuntu-20.04'
            php: '8.1'
            experimental: true

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php: ${{ matrix.php }}
          extensions: none
          coverage: none

      - name: Install Pandoc
        run: |
          sudo apt install pandoc
          pandoc --version

      - name: Install Composer dependencies
        run: composer install --no-progress

      - name: Run PHPUnit
        run: vendor/bin/simple-phpunit
